File "/usr/demos/cvpr/rgbd/benchmark/rgbd_benchmark_tools/src/rgbd_benchmark_tools/evaluate_rpe.py", line 182, in evaluate_trajectory
    raise Exception("Couldn't find matching timestamp pairs between groundtruth and estimated trajectory!")
Exception: Couldn't find matching timestamp pairs between groundtruth and estimated trajectory!
